### PR TITLE
Menu: reduce code size

### PR DESCRIPTION
**Pull request by wutje**
Refactor the code to replace if + strcpy code to a ? : construction.

### CODE REVIEW

**Comment by JuantAldea** [comment]
It puzzles me that [391de53](https://github.com/egzumer/uv-k5-firmware-custom/pull/347/commits/391de53e01e24d7bff5e8399b000c1ec61e55693) could actually reduce the binary size. I would expect the compiler to generate code equivalent to what you have done, given that the string pointer is just an alias in the end.

**Comment by wutje** [comment]
> It puzzles me that [391de53](https://github.com/egzumer/uv-k5-firmware-custom/pull/347/commits/391de53e01e24d7bff5e8399b000c1ec61e55693) would actually reduce the binary size. I would expect the compiler to generate code equivalent to what you have done, given that the string pointer is just an alias in the end, and anyway it has to pick one of the addresses.

Ah. Yes.
I made that commit before you changed the code to an intermediate pointer.
It now makes less sense.

**Comment by egzumer** [comment]
391de53e01e24d7bff5e8399b000c1ec61e55693 - It doesn't do anything in terms of memory usage, and the old implementation is more readable to me.

I cherrypicked other 2 commits

**Comment by wutje** [comment]
> 391de53e01e24d7bff5e8399b000c1ec61e55693 - It doesn't do anything in terms of memory usage, and the old implementation is more readable to me.
> 
> I cherrypicked the other 2 commits

Thank you for merging this.
I totally agree on dropping the now pointless commit.

**Pull request closed without merging**
