### PR TITLE
settings

### PR DESCRIPTION
**Pull request by gartnl**
selectable FM broadcast range

### CODE REVIEW

**Comment by darman6hlg** [comment]
Nice

**Comment by gartnl** [comment]
**Do not commit yet!!!!** 
After extensive testing I ran into a problem. 
Disregard this and throw away. I will check wat is wrong first.

**Comment by egzumer** [comment]
There is a band selection register in the BK1080 that has to be set properly.

**Comment by gartnl** [comment]
> There is a band selection register in the BK1080 that has to be set properly.

I know, but that was not the point, and would have been the next step to address: the selectable band edges would also determine the driver settings.
The first goal was to set band edges, esp the lower edge, to prevent autoscan from starting outside the region. E.g. in Europe starting at 76 stores several frequencies that are not broadcast but just random signals. So the first 5 or 6 memory positions were taken by these signals.

I placed the 'region' variable I used to set the band edges inside the unused bytes of the structure used for FM functions in 'settings' and removed the remaining padding and also the memset to fill the structure to save with 0xff.
That worked, as did the adapted CHIRP driver, but as soon as a memory channel is saved during an autoscan in the HT this byte got somehow overwritten.

Never mind, I'll keep looking in to it for my own version.

**Pull request closed without merging**
