### PR TITLE
some nicer looking fonts

### PR DESCRIPTION
**Pull request by curselink**
Terminus for alphabet and bigDigits ported from russian UVMOD

### CODE REVIEW

**Comment by curselink** [comment]
preview

**Comment by mbgroot** [comment]
[font.c.txt](https://github.com/egzumer/uv-k5-firmware-custom/files/12831094/font.c.txt)
i make small bold too
and big digits as default font, VCR as option

**Comment by curselink** [comment]
> [font.c.txt](https://github.com/egzumer/uv-k5-firmware-custom/files/12831094/font.c.txt) i make small bold too and big digits as default font, VCR as option
great work, these new bold font looks nice, can you also do the default gFontSmall one?

**Comment by mbgroot** [comment]
[font.c.txt](https://github.com/egzumer/uv-k5-firmware-custom/files/12837182/font.c.txt)
I already did _gFontSmall_, added it to the file.

**Comment by curselink** [comment]
oh sorry, i didn't notice, i took your word that its only gFontSmallBold that is modified, my bad

**Comment by mbgroot** [comment]
> oh sorry, i didn't notice, i took your word that its only gFontSmallBold that is modified, my bad

gFontSmall - I added to the file just today. just made it earlier, for the original firmware.

**Comment by curselink** [comment]
> > oh sorry, i didn't notice, i took your word that its only gFontSmallBold that is modified, my bad
> 
> gFontSmall - I added to the file just today. just made it earlier, for the original firmware.

i see that you modified the `gFontSmallDigits[11][7]`, however in egzumer, on in general, oneofeleven's `font.c`, it is commented out and it seems that the firmware uses the `gFontSmall[95][6]` in menu, frequency in NAME + FREQ, and other places, regardless of `ENABLE_SMALL_BOLD`

**Comment by mbgroot** [comment]
> i see that you modified the `gFontSmallDigits[11][7]`, however in egzumer, on in general, oneofeleven's `font.c`, it is commented out and it seems that the firmware uses the `gFontSmall[95][6]` in menu, frequency in NAME + FREQ, and other places, regardless of `ENABLE_SMALL_BOLD`

I changed 4 fonts: gFontBig, gFontBigDigits, gFontSmallDigits, gFontSmallBold. the file is attached above. the font from Russian UVMOD was also redrawn by me.

**Pull request closed without merging**
