### PR TITLE
Use __WFI to put the core to rest instead of always spin-locking & some refactorings

### PR DESCRIPTION
**Pull request by JuantAldea**

### CODE REVIEW

**Comment by egzumer** [comment]
The _WFI modifies delays, see longpress button beeps as an example, significantly different. I don't know how that would influence other things, and the power consumption reduction is negligible.

nosleep jpg channel 1_nosleep jpg channel 1_xfm_0

**Comment by JuantAldea** [comment]
Interesting... makes me wonder if __WFE is enough to make it enter sleep. The main loop does indeed loops at 10Hz, I've checked that by printing.

**Comment by egzumer** [comment]
1o11 has WFI implemented, although I didn't check how it works there.

**Comment by JuantAldea** [comment]
I did not close this... so how come? :O

**Comment by egzumer** [comment]
No idea :)
Looks like it might get automatically closed when you force pushed last commit.

**Pull request closed without merging**
