### PR TITLE
AubsUK - Added Scan option to scan List1, List2, All Channels, All Lists, No Lists

### PR DESCRIPTION
**Pull request by AubsUK**
Added Scan option to scan List1, List2, All Channels, All Lists, No Lists

- Gives a slightly different way to scan channels.
- Allows channels to excluded from any list, so when scanning ALL LISTS, only channels in a list are included (The original reason the PR was created).
- An unintended (but useful) result, it technically gives a third list ("not in any list") that can be scanned separately from the two predefined lists.

### Key
<table>
<tr>
<th>Entry in <br />Menu Item 19<br />(SList)</th>
<th>Scan Status<br />(top right)</th>
<th>Purpose</th>
</tr>
<tr>
<td>LIST1</td>
<td>1</td>
<td>Scan through all channels added to **LIST1**</td>
</tr>

<tr>
<td>LIST2</td>
<td>2</td>
<td>Scan through all channels added to **LIST2**</td>
</tr>

<tr>
<td>ALL CHANNELS</td>
<td>C</td>
<td>Scan through **all** channels (List1, List2, and channels not added to any list)<br />[this is the old "*"]</td>
</tr>

<tr>
<td>ALL LISTS</td>
<td>L</td>
<td>Scan through all channels added to List1 **or** List2</td>
</tr>

<tr>
<td>NO LISTS</td>
<td>N</td>
<td>Scan through all channels that are **not in** both List1 and List2</td>
</tr>
</table>

The build it is based on (live build) Firmware uses 98.19% of available memory (60324/61439 bytes).
My build including this Pull Request  Firmware uses 98.32% of available memory (60404/61439 bytes).
+80 bytes, (98.19% to 98.32% = 0.13%)

It only uses 80 bytes more for the additional functionality

### CODE REVIEW

**Comment by qsus** [comment]
You might also consider the intersection of List1 and List2 (channels which are in BOTH List1 and List2).
But at this point, you might as well add couple more lists :)

**Comment by AubsUK** [comment]
@qsus I had a brief look at adding new lists, but I think it's a lot more involved, and use too much of the little memory left. I will continue to look into it though.

The intersection between L1 and L2, while a good idea (I thought about it too!), looks to just add extra complexity that I don't think anyone would be interested in, and it would take a bit more space.

**Comment by qsus** [comment]
There are like 8 or more combinations you can have with 2 lists, but the only useful ones in my opinion are: L1, L2, L1+L2 and All; adding other combinations isn't useful imo.
Adding more lists would make sense in my opinion though, unless it's too complicated.

**Comment by AubsUK** [comment]
You don't think it's useful to only scan all channels, as long as they're in any of the lists? In addition to All Channels (*) which currently scans every channel, even if it's not in a list.

The issue I faced was that I have some repeaters that are out of range for my normal location that I want to have programmed in, but at my location, those freqs are full of interference, so I didn't want them to be scanned normally. Removing them from any List means they can be scanned separately (No Lists).

**Comment by qsus** [comment]
The NO LIST option might make sense in some specific use case like yours, but I think generally adding two more lists would be way more useful. Scan options would then be List x, All lists and All channels.

**Comment by AubsUK** [comment]
Problem with these radios is the lack of storage space for the firmware, and @egzumer has done a great job to fit everything in with the limited space.

> adding two more lists would be way more useful. Scan options would then be List x, All lists and All channels.

Thanks for the feedback. Do you think it would be better (if possible) to have say 4 (or more) lists, but each channel would only being able to be in 1 list? I think it would use too much space to add more lists, but removing the List1/List2 options and having one List option could balance that out.

And then when scanning, have the option to turn each list on/off, so one or more list like 1, 2, 3, 4, 12, 123, 1234, 124, 134, 14, 23, 234, 24, 34, All Channels (obviously All Lists would be the 1234 option).

If that were possible, I think because there would be 15 combinations, the only reasonable way to switch lists on/off would be to press `*1`, `*2` etc., but that would mean pressing and holding `*`  wouldn't be able to be used to switch between them.

**Comment by qsus** [comment]
Ok, sorry for replying after so long. To sum up:
1. Your current solution is better than the previous and I use it.
2. Then there is a solution where each channel can be stored in any number of four lists (1, 12, 13, 14, 123, ...). You can then choose which list to scan or to scan all channels.
3. Another solution is the one you mentioned in the above comment. Each channel would be stored in exactly one of X lists (none is effectively another list) and you could choose which combination of multiple channels to scan. This might be the best solution and I would love to see it working.
4. Or you can combine both previous solutions (2+3), but that might get too confusing for the user and take up too much space.

I haven't read the code so I don't understand exactly how the available space works, but I believe the solution you proposed (3) should be possible, especially because it should, in theory, require the same amount of space (2 bits per channel) if using 4 lists.

**Comment by AubsUK** [comment]
Thanks @qsus , I'm looking into adding 10 lists if I can, but I have a feeling it might not be possible.  My plan would be:

Search as normal (press and hold scan to start)
Use up and down to change direction as normal
While scanning, press 1 to 0 to turn on or off lists 1,2,3,4,5,6,7,8,9,0

Menu >> List >> set the list for the stored channel (only 1 per channel)

There will be no way to store a default search list as they will be whatever you last set them.

I'm also looking to see if I can get it to auto scan from start.

The only issue I've come across so far, I've asked in [Discussion 468](https://github.com/egzumer/uv-k5-firmware-custom/discussions/468).

**Comment by qsus** [comment]
If you can do that, it would be great!

**Comment by AubsUK** [comment]
> If you can do that, it would be great!

It's looking pretty promising for 10 lists (each would be individually controlled and each channel can be in none, one or more list).

So far, I've got each of the 200 channels to be able to be in any of the 0-9 lists and each list status stored.

I've not yet got scanning running or turning each list on/off while scanning, but they should be relatively simple to code, if I can make it small enough to fit. Hopefully tomorrow I'll have something to show.

**Comment by egzumer** [comment]
https://github.com/egzumer/uv-k5-firmware-custom/discussions/485

**Pull request closed without merging**
